src/Amap/MainBundle/Entity/PanierAbstract.php
<?php

namespace Amap\MainBundle\Entity;

abstract class PanierAbstract
{
    // Force les classes filles à définir cette méthode
    abstract public function getId();
    abstract public function getCreatedAt();
    abstract public function getPrice();
    abstract public function getDiscountedPrice();
    
	public function __toString() 
	{
		if($this->getCreatedAt() instanceof \DateTime) {
			return (string) $this->getId().' - '.$this->getCreatedAt()->format('d/m/Y').' - '.$this->getPriceFormat().$this->getDevise();
		}
		return (string) 'Nouveau Panier';
	}
	
	public function getPriceFormat()
	{
		return number_format($this->getPrice(), 2, ',', ' ');
	}
	
	public function getDiscountedPriceFormat()
	{
		return number_format($this->getDiscountedPrice(), 2, ',', ' ');
	}
	
	public function getDevise()
	{
		return '€';
	}
    
}

src/Amap/MainBundle/Entity/ProductVegetable.php
<?php

namespace Amap\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * ProductVegetable
 *
 * @ORM\Table(name="product_vegetable")
 * @ORM\Entity(repositoryClass="Amap\MainBundle\Entity\Repository\ProductVegetableRepository")
 * 
 * @UniqueEntity(fields={"title"})
 */
class ProductVegetable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=100, nullable=false, unique=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=500, nullable=true)
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
	 * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updatetd_at", type="datetime", nullable=true)
	 * @Gedmo\Timestampable(on="update")
     */
    private $updatetdAt;
	
	/**
	 * @ORM\OneToMany(targetEntity="Product", mappedBy="productVegetable")
	 */
	protected $products;
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Image", inversedBy="productVegetable")
     * @ORM\JoinTable(name="product_vegetable_has_image",
     *   joinColumns={
     *     @ORM\JoinColumn(name="product_vegetable_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="image_id", referencedColumnName="id")
     *   }
     * )
     */
    private $image;

    
    /**
     * Constructor
     */
    public function __construct()
    {
        
    }
    
	public function __toString() {
		return (string) $this->title;
	}
	
	
	public function getAvgPrices()
	{
		$pricesByQuantity = array();
		
		if(!$this->products) {
			return $pricesByQuantity;
		}
		
		foreach ($this->products as $key => $product) 
		{
			$price = $product->getPrice();
			$quantityLab = $product->getQuantityType()->getTitle();
			$quantityVal = $product->getQuantity();
			
			// On convertit en Kg les grammes :
			if(strtolower($quantityLab) == 'g') {
				$quantityVal = $quantityVal /1000;
				$quantityLab = 'Kg';
			}
			
			$pricesByQuantity[ $quantityLab ][] = $price / $quantityVal; 
		}
		
		foreach ($pricesByQuantity as $quantity => $prices) 
		{
			$count = count($prices);
			$sum = array_sum($prices);
			$avg = $sum / $count;
			
			$pricesByQuantity[$quantity]['avg'] = $avg;
		}
		
		return $pricesByQuantity;
	}
    

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Product
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Product
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatetdAt
     *
     * @param \DateTime $updatetdAt
     * @return Product
     */
    public function setUpdatetdAt($updatetdAt)
    {
        $this->updatetdAt = $updatetdAt;
    
        return $this;
    }

    /**
     * Get updatetdAt
     *
     * @return \DateTime 
     */
    public function getUpdatetdAt()
    {
        return $this->updatetdAt;
    }


    /**
     * Add products
     *
     * @param \Amap\MainBundle\Entity\Product $products
     * @return ProductVegetable
     */
    public function addProduct(\Amap\MainBundle\Entity\Product $products)
    {
        $this->products[] = $products;
    
        return $this;
    }

    /**
     * Remove products
     *
     * @param \Amap\MainBundle\Entity\Product $products
     */
    public function removeProduct(\Amap\MainBundle\Entity\Product $products)
    {
        $this->products->removeElement($products);
    }

    /**
     * Get products
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Add image
     *
     * @param \Amap\MainBundle\Entity\Image $image
     * @return ProductVegetable
     */
    public function addImage(\Amap\MainBundle\Entity\Image $image)
    {
        $this->image[] = $image;
    
        return $this;
    }

    /**
     * Remove image
     *
     * @param \Amap\MainBundle\Entity\Image $image
     */
    public function removeImage(\Amap\MainBundle\Entity\Image $image)
    {
        $this->image->removeElement($image);
    }

    /**
     * Get image
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getImage()
    {
        return $this->image;
    }
}

src/Amap/MainBundle/Controller/DefaultController.php
<?php

namespace Amap\MainBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Amap\MainBundle\Form\ContactType;
use Amap\MainBundle\Form\PermanenceType;
use Symfony\Component\Form\FormError;


class DefaultController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        
        $accueil = $em->getRepository('AmapMainBundle:Article')->findHome();
		
        return $this->render('AmapMainBundle:Default:index.html.twig', array(
            'accueil' => $accueil
        ));
    }
	
	public function searchAction(Request $request)
	{
		$em = $this->getDoctrine()->getManager();
		
		$search = $request->request->get('search');
		
        $entities = $em->getRepository('AmapMainBundle:Article')->search(array('search' => $search));
        
        return $this->render('AmapMainBundle:Default:search_result.html.twig', array(
            'entities'      => $entities,
            'search'        => $search,
        ));
	}
	
	public function nextPanierAction()
	{
		$em = $this->getDoctrine()->getManager();
		
		$delivery = $em->getRepository('AmapMainBundle:Delivery')->findNextOneWithJoin();
        
		return $this->render('AmapMainBundle:Default:next_panier.html.twig', array(
            'delivery'      => $delivery,
        ));
	}
	
    public function nextPanierAddonsAction()
    {
        $em = $this->getDoctrine()->getManager();
        
        $deliveries = $em->getRepository('AmapMainBundle:Delivery')->findNextPanierAddons();
        
        return $this->render('AmapMainBundle:Default:next_panier_addons.html.twig', array(
            'deliveries'      => $deliveries,
        ));
    }
    
	public function pluploadAction(Request $request)
	{
		$em = $this->getDoctrine()->getManager();
		
		$file = $request->files->get('file');
		$post = json_decode( $request->request->get('json') );
		
		$ref = $request->request->get('ref');
		$dir = $request->request->get('dir');
		$article_id = $request->request->get('article_id');
		
		
		if($file->getError() != 0 || !$post) {
			$response = new Response( '{"error": true, "message": "Une erreur est survenue"}' );
	        $response->headers->set('Content-Type', 'application/json');
	        return $response;
		}
		
		$current = null;
		foreach ($post as $key => $arr) 
		{
			if($arr->filename == $file->getClientOriginalName()) {
				//echo $arr->filename .' == '. $file->getClientOriginalName();
				$current = $key;
			}
		}
		// print_r($post);
		// print_r($current); die();
		if($current === null) 
		{
			$debug = array(
				'current' => $current,
				'getClientOriginalName' => $file->getClientOriginalName(),
				'postJSON' => $post,
			);
			$response = new Response( '{"error": true, "message": "Une erreur est survenue", "debug": '.json_encode($debug).'}' );
	        $response->headers->set('Content-Type', 'application/json');
	        return $response;
		}
		
		$image = new \Amap\MainBundle\Entity\Image();
		$image->setFile( $file );
		$image->upload();
		
		$image->setTitle( $post->$current->title )->setAlt( $post->$current->alt );
		
		if($file->getError() != 0) {
			$response = new Response( '{"error": true, "message": "Une erreur est survenue"}' );
	        $response->headers->set('Content-Type', 'application/json');
	        return $response;
		}
		
		if($article_id && $article_id > 0) {
			$article = $em->getRepository('AmapMainBundle:Article')->find( $article_id );
			$article->addImage( $image );
		}

		$avalancheService = $this->get('imagine.cache.path.resolver');
		$cachedImage = $avalancheService->getBrowserPath($image->getWebPath(), 'my_thumb');
		
		$em->persist( $image );
		$em->flush();
		
		$response = new Response( '{"error": false, "message": "Upload OK", "image_id": '.$image->getId().', "web_path": "'.$cachedImage.'"}' );
        $response->headers->set('Content-Type', 'application/json');
        return $response;
			
		// print_r($file); 
		// print_r($post); die();
	}

	public function contactAction(Request $request)
    {
        //if($request->getSession()->has('messageSent')) 
    	$form = $this->createForm(new ContactType());
        
        if ('POST' == $request->getMethod()) 
        {
            $form->bind($request);
            if ($form->isValid()) 
            {
            	$data = $form->getData();
				
				$message = \Swift_Message::newInstance()
					->setSubject('Contact - Amap')
					->setFrom( $data['email'] )
					->setTo( $this->container->getParameter('email') )
					->setCharset('UTF-8')    
					->setContentType('text/html')
					->setBody($this->renderView('AmapMainBundle:Default:contact_mail.html.twig', array('data' => $data)))
				;
				
				$this->get('mailer')->send($message); 
				
				$session = $this->get("session"); //$request->getSession();
				$session->getFlashBag()->add('messageSent', 'Votre message a bien été envoyé.');	
				
				// Redirect - This is important to prevent users re-posting
            	// the form if they refresh the page
				return $this->redirect($this->generateUrl('contact'));
				
			}
		}
		
		return $this->render('AmapMainBundle:Default:contact.html.twig', array(
			'form' => $form->createView(),
		));
	}

	
	public function createPermanenceAction(Request $request)
	{
		if(!$request->isXmlHttpRequest()) {
			throw $this->createNotFoundException('La requête doit être de type XHR.');
		}
		
        $jsonResp = array();
		$form = $this->createForm(new PermanenceType());
		
		$form->bind($request);
		
        if ($form->isValid()) 
        {
        	$em = $this->getDoctrine()->getManager();
			
        	$user = $this->getUser();
        	$post = $request->request->get('amap_mainbundle_permanencetype');
        	
			$date = new \DateTime( $post['deliveryDate'] );
			
			$entity = $em->getRepository('AmapMainBundle:Permanence')->findOneBy( array('deliveryDate' => $date) );
			
			// La permanence n'existe pas, on la créé :
			if(!$entity) 
			{
				$entity = $form->getData();
				$entity->setDeliveryDate( $date );
				$entity->setUserDetail( array( $user->getId() => array($post['heure'])) );
				$em->persist( $entity );
				
				$user->addPermanence( $entity );
                
                $jsonResp = array(
                    'returnState' => 'ok',
                );
			}
			// La permanence existe :
			else 
			{
				if($entity->getIs18Full() && $post['heure'] == 18) 
				{
				    $jsonResp = array( 
				        "error" => true, 
				        "message" => "Il n\'y a plus de places pour 18h.", 
				        "returnState" => "remove"
                    );
					return $this->createJsonResponse( $jsonResp );
				}
				if($entity->getIs19Full() && $post['heure'] == 19) 
				{
				    $jsonResp = array( 
				        "error" => true, 
				        "message" => "Il n\'y a plus de places pour 19h.", 
				        "returnState" => "remove",
                    );
                    return $this->createJsonResponse( $jsonResp );
				}
				
				$detail = $entity->getUserDetail();
				
				// Le user est dèjà rattaché à cette perm :
				if($user->hasPermanence( $entity->getId() ))
				{
				    // Le user fait les 2h de permanences :
					if(!in_array($post['heure'], $detail[$user->getId()]))
					{
						$detail[$user->getId()][] = $post['heure'];
						$entity->setUserDetail( $detail );
                        
                        $jsonResp = array(
                            'returnState' => 'ok',
                        );
					}
					else 
					{
					    $jsonResp = array(
                            'error' => true, 
                            'message' => 'Vous êtes déjà inscrit à '.$post['heure'],
                            'returnState' => 'remove',
                        );
						return $this->createJsonResponse( $jsonResp );
					}
				}
				// Le user n'est pas encore rattaché à cette perm :
				else 
				{
					$user->addPermanence( $entity );
					$detail[$user->getId()][] = $post['heure'];
					$entity->setUserDetail( $detail );
                    
                    $jsonResp = array( 
                        'returnState' => 'ok',
                    );
				}
			}
			
			
			$em->flush();
			
			$inscriptionTxt = $user->getFirstName().' '.$user->getLastName().' à '.$post['heure'].'h';
			$fullInscriptionTxt = 'Vous vous êtes inscrits à la permanence du mardi '.$entity->getDeliveryDate()->format('d/m/Y').' à '.$post['heure'].'h';
            
            $jsonResp = array_merge( array(
                "fullInscription" => trim($fullInscriptionTxt), 
                "inscription" => trim($inscriptionTxt), 
                "usersCountClass" => $entity->getUsersCountClass(), 
                "is18Full" => $entity->getIs18Full('txt'),
                "is19Full" => $entity->getIs19Full('txt'),
                "returnState" => 'remove',
            ), $jsonResp);
            return $this->createJsonResponse( $jsonResp );
		}
		// echo "<pre>";
		// print_r($form->getErrors());
		// die();
		
		$err = $this->implode_r(' | ', $this->getErrorMessages($form));
		
        // Form is not valid :
        $jsonResp = array(
            "error" => true, 
            "message" => "Une erreur est survenue : ".$err,
        );
		return $this->createJsonResponse( $jsonResp );
	}
	
	public function mergeJsonResponse($jsonResp)
	{
    	return json_encode( array_merge( array(
            'error' => false,
            'message' => '',
            'fullInscription' => '',
            'inscription' => '',
            'usersCountClass' => 0,
            "is18Full" => false, 
            'is19Full' => false,
            'returnState' => '',
            'showMessage' => false,
        ), $jsonResp));	
	}
	
	public function createJsonResponse($jsonResp)
	{
        $response = new Response( $this->mergeJsonResponse($jsonResp) );
        $response->headers->set('Content-Type', 'application/json');

src/Amap/MainBundle/Resources/views/Default/contact.html.twig
{% extends 'AmapMainBundle::layout.html.twig' %}


{% block title %}
    {{ parent() }} - Contact
{% endblock %}


{% block endPage %}
    {{ parent() }}
	{{ tinymce_init() }}
{% endblock %}


{% block content %}

	<h1>Contact</h1>
	
	   
    
	{% if app.session.flashbag.has('messageSent') %}
	
        <div class="alert alert-success">
        	{% for flashMessage in app.session.flashbag.get('messageSent') %}

                {{ flashMessage }}

            {% endfor %}
        </div>
        
    {% else %}
        
        {% form_theme form 'AmapMainBundle:Form:fields.html.twig' %}
    
        {{form_errors(form)}}
    
		<div class="box">
		<form class="clearfix form" action="{{ path('contact')}}" method="post" {{ form_enctype(form) }}>
			
			{# form_widget(form) #}
			
			<div class="left">
				{{ form_row(form.civilite) }}
				{{ form_row(form.prenom) }}
				{{ form_row(form.nom) }}
				{{ form_row(form.email) }}
				{{ form_row(form.tel) }}
			</div>
			
			<div class="right">
				{{ form_row(form.sujet) }}
				{{ form_row(form.message) }}
				<input class="btn btn-success" type="submit" value="Envoyer" />
			</div>
			
			{{ form_rest(form) }}
			<br class="clear" />
			
		</form>
		</div>
	{% endif %}
	
{% endblock content %}

src/Amap/MainBundle/Resources/views/Default/contact_mail.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        
        <style type="text/css">
            body {
                font-family: Arial, Helvetica, sans-serif;
            }
            h1 {
                margin-bottom:10px;
                padding-bottom:10px;
            }
            p {
                margin-bottom:5px;
                padding-bottom:5px;
            }
            
        </style>
        
    </head>
    
    <body>
        
        <h1>
        Contact Amap d'Issy et d'ailleurs
        </h1>
        
        <p>
        {{ data.civilite }}
        {{ data.nom }}
        {{ data.prenom }}
        </p>
        
        <p>
        {{ data.email }}
        {{ data.tel }}
        </p>
        
        <p>
        {{ data.sujet }}
        {{ data.message }}
        </p>

    </body>
</html>

src/Amap/MainBundle/Resources/views/Default/index.html.twig
{% extends 'AmapMainBundle::layout.html.twig' %}


{% block content %}
    
    <h1>{{accueil.title}}</h1>
    
    <div class="slider-wrapper theme-default">
	    <div id="slider" class="nivoSlider">
	    	{% for img in accueil.image %}
		    	{% set webPath = '/' ~ img.webPath %}
		        <img src="{{ webPath | apply_filter('home_thumb') }}" alt="{{img.alt}}" />
	        {% endfor %}
	    </div>
    </div>
	<div id="htmlcaption" class="nivo-html-caption">
	    <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
	</div>
    
    {{accueil.content | raw}}
    
{% endblock %}


{% block head %}
    {{ parent() }}
    
    {% stylesheets 
       '@AmapMainBundle/Resources/public/nivo-slider/nivo-slider.css' 
       '@AmapMainBundle/Resources/public/nivo-slider/themes/default/default.css' 
    %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}


{% block endPage %}
    {{ parent() }}
    
    {% javascripts 
        '@AmapMainBundle/Resources/public/nivo-slider/jquery.nivo.slider.pack.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    
    <script type="text/javascript">
	$(window).load(function() {
	    $('#slider').nivoSlider({
	        effect: 'random', // Specify sets like: 'fold,fade,sliceDown'
	        slices: 15, // For slice animations
	        boxCols: 8, // For box animations
	        boxRows: 4, // For box animations
	        animSpeed: 500, // Slide transition speed
	        pauseTime: 3000, // How long each slide will show
	        startSlide: 0, // Set starting Slide (0 index)
	        directionNav: true, // Next & Prev navigation
	        controlNav: true, // 1,2,3... navigation
	        controlNavThumbs: false, // Use thumbnails for Control Nav
	        pauseOnHover: true, // Stop animation while hovering
	        manualAdvance: false, // Force manual transitions
	        prevText: 'Prev', // Prev directionNav text
	        nextText: 'Next', // Next directionNav text
	        randomStart: false, // Start on a random slide
	        beforeChange: function(){}, // Triggers before a slide transition
	        afterChange: function(){}, // Triggers after a slide transition
	        slideshowEnd: function(){}, // Triggers after all slides have been shown
	        lastSlide: function(){}, // Triggers when last slide is shown
	        afterLoad: function(){} // Triggers when slider has loaded
	    });
	});
	</script>
{% endblock %}

src/Amap/MainBundle/Resources/views/Default/next_panier.html.twig

{% if delivery is defined and delivery is not empty %}
<div class="well">
	<h4>
		Notre prochain Panier
		<a class="btn margin-left" href="{{ path('delivery_show', {'id': delivery.id}) }}">
			<i class="icon-eye-open"></i>
		</a>
	</h4>
	
    <ul class="nav nav-list">
    
	    <li class="nav-header">{{delivery.deliveredAt | localizeddate('medium', 'none') }}</li>
	    
	    {% set products = delivery.panierMaxi.product %}
	    
	    {% for k, product in products %}
	        <li>
	        	<i class="icon-leaf"></i> 
	        	{{product.title}}
	        </li>
	    {% endfor %}
	    
	    {% if app.user is not null and app.user.nbEggs > 1 and delivery.withEggs %}
	       <li class="text-warning">
	       	   <i class="icon-hand-right"></i>
	           <strong>{{app.user.nbEggs}} Oeufs</strong>
	       </li>
	    {% endif %}
	</ul>
	    
	
	{% set panierAddon = delivery.panierAddon %}
	{% set plength = panierAddon|length %}
	
    {% if plength > 0 %}
        <hr class="divider" />
        
        <h4 class="text-success">
        	<i class="icon-star"></i>
        	Commande{% if plength>1 %}s{% endif %} exceptionnelle{% if plength>1 %}s{% endif %} !
        </h4>
        
        <div class="panier_addon">
        {% for panier in delivery.panierAddon %}
            <ul class="nav nav-list">
            {% for product in panier.product %}
                <li>
                	<i class="icon-leaf"></i>
                    {{product.title}}
                </li>
            {% endfor %}
            </ul>
            <div class="control-group">
            <a href="{{ path('commande_new', {'panierAddon': panier.id, 'delivery': delivery.id}) }}" class="btn btn-success">
            	<i class="icon-shopping-cart"></i>
            	Je commande
            </a>
            </div>
        {% endfor %}
        </div>
   {% endif %}
	        
    
</div>
{% endif %}

src/Amap/MainBundle/Resources/views/Default/next_panier_addons.html.twig

{% if deliveries is defined and deliveries is not empty %}

{% if deliveries|length > 1 %}
    {% set pluriel = 's' %}
{% else %}
    {% set pluriel = '' %}
{% endif %}

<div class="well">
	
	<h4>
		Prochaine{{pluriel}} commande{{pluriel}} exceptionnelle{{pluriel}}
	</h4>
	
	
	
	{% for delivery in deliveries %}
	
		{% set panierAddon = delivery.panierAddon %}
		{% set plength = panierAddon|length %}
		
		{#
	    <h5 class="text-success">
	    	<i class="icon-star"></i>
	    	Commande{% if plength>1 %}s{% endif %} exceptionnelle{% if plength>1 %}s{% endif %} !
	    </h5>
	    #}
	    
	    <div class="panier_addon">
	    {% for panier in delivery.panierAddon %}
	        <ul class="nav nav-list">
		        <li class="nav-header">
			        <small>
			        	<i class="icon-calendar"></i>
			            Livraison le : 
			            {{ delivery.deliveredAt | localizeddate('medium', 'none') | label('success') }}
			        </small>
		        </li>
	        {% for product in panier.product %}
	            <li>
	            	<i class="icon-leaf"></i>
	                {{product.title}}
	            </li>
	        {% endfor %}
	        </ul>
	        
	        <div class="control-group">
		        <a href="{{ path('commande_new', {'panierAddon': panier.id, 'delivery': delivery.id}) }}" class="btn btn-success">
		        	<i class="icon-shopping-cart"></i>
		        	Je commande
		        </a>
	        </div>
	        
	    {% endfor %}
	    </div>
	    
        {% if not loop.last %}
           <hr class="divider" />
        {% endif %}
        
    {% endfor %} {# deliveries #}
    
</div>
{% endif %}

src/Amap/MainBundle/Resources/views/Default/nos_produits.html.twig
{% extends 'AmapMainBundle::layout.html.twig' %}


{% block title %}
    {{ parent() }} - Nos Produits
{% endblock %}


{% block content %}

	{% if products %}
	<table class="table table-striped table-hover table-bordered">
        <caption><span class="label label-success">Bio</span></caption>
        <thead>
            <tr>
                <th colspan="2">
                	<i class="icon-leaf"></i>
                    Nos Produits
                </th>
                <th class="aright">
                	Prix moyen
                </th>
                <!--
                <th class="aright">
                    Apparu le
                </th>
                -->
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td><strong>{{product.title}}</strong></td>
                <td>
                	{% if product.image | length > 0 %}
	                	{% for img in product.image %} 
	                	
			                {% set webPath = '/' ~ img.webPath %}
		                    <a class="thumbnail pull-left{% if not loop.first %} hide{% endif %}"  href="{{ webPath }}" rel="prettyPhoto[galery][{{product.title}}]" title="{{img.title}}">
		                       <img src="{{ webPath | apply_filter('small_thumb') }}" alt="{{img.alt}}" /><!-- class="img-circle" --> 
		                    </a>
		                    
			            {% endfor %}
                	{% endif %}
                	
                	<p class="pull-left clearfix margin-left">
                	<small><i>{{product.description}}</i></small>
                	</p>
                </td>
                <td class="aright">
                	{% for q, prices in product.avgPrices %}
                	   <small>{{prices.avg | number_format(2, ',', ' ')}}€ / {{q}}</small> <br />
                	{% endfor %}
                </td>
                <!--
                <td class="aright">{{product.createdAt | localizeddate('medium', 'none') }}</td>
                -->
            </tr>
            {% endfor %}
        </tbody>
        
    </table>	
    {% endif %}
    
{% endblock content %}


{% block head %}
    {{ parent() }}
    
    {% stylesheets 
       '@AmapMainBundle/Resources/public/pretty-photo/css/prettyPhoto.css'  
    %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}


{% block endPage %}
    {{ parent() }}
    
    {% javascripts 
        '@AmapMainBundle/Resources/public/pretty-photo/js/jquery.prettyPhoto.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({'theme': 'facebook'});
      });
    </script>
    
{% endblock %}

src/Amap/MainBundle/Resources/views/Default/search_result.html.twig
{% extends 'AmapMainBundle::layout.html.twig' %}

{% block title %}
    {{parent()}}
    - Résultat(s) de recherche(s)
{% endblock %}

{% block content %}
    
    {% if entities|length > 1 %} {% set pluriel = 's' %}
    {% else %} {% set pluriel = '' %} {% endif %}
    
    <h1>{{entities|length}} Résultat{{pluriel}} &laquo; {{search}} &raquo;</h1>
    
    {% include 'AmapBlogBundle:Article:_list.html.twig' %}
    
{% endblock %}